import{S as l}from"./assets/vendor-874053e3.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function e(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(t){if(t.ep)return;t.ep=!0;const r=e(t);fetch(t.href,r)}})();function m(o){const s=new URLSearchParams({key:API_KEY,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0});return loader.style.display="block",fetch(`${BASE_URL}?${s}`).then(e=>{if(!e.ok)throw new Error("Network response was not OK!");return e.json()}).then(e=>(loader.style.display="none",e.hits.length===0&&iziToast.error({fontSize:"large",close:!1,position:"topRight",messageColor:"white",timeout:2e3,backgroundColor:"red",message:"Sorry, there are no images matching your search query. Please try again!"}),e)).catch(e=>console.error("Error fetching data:",e))}function u(o){const s=o.hits.map(e=>`<div class="gallery-item">
      <a class="gallery-link" href="${e.largeImageURL}">
          <img class="gallery-image" src="${e.webformatURL}" alt="${e.tags}">
      </a>
      <div class="gallery-image-info">
          <p class="image-info-item"><span class="image-items-text">Likes: </span>${e.likes}</p>
          <p class="image-info-item"><span class="image-items-text">Views: </span>${e.views}</p>
          <p class="image-info-item"><span class="image-items-text">Comments: </span>${e.comments}</p>
          <p class="image-info-item"><span class="image-items-text">Downloads: </span>${e.downloads}</p>
      </div>
  </div>`).join("");container.innerHTML=s,lightbox.refresh()}const c=document.querySelector("#searchForm"),f=document.querySelector(".gallery");document.querySelector(".loader");let n="";new l(".gallery-link",{captionsData:"alt",captionDelay:250});c.addEventListener("submit",p);function p(o){o.preventDefault(),f.innerHTML="",n=c.elements.searchQuery.value.trim(),m(n).then(s=>u(s))}
//# sourceMappingURL=commonHelpers.js.map
