import{S as c}from"./assets/vendor-874053e3.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))e(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&e(a)}).observe(document,{childList:!0,subtree:!0});function s(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function e(t){if(t.ep)return;t.ep=!0;const o=s(t);fetch(t.href,o)}})();const l="42569915-bcd29008899db620988a57306",u="https://pixabay.com/api/";document.querySelector(".loader");function m(i,r){const s=new URLSearchParams({key:l,q:i,image_type:"photo",orientation:"horizontal",safesearch:!0});return r.style.display="block",fetch(`${u}?${s}`).then(e=>{if(!e.ok)throw new Error("Network response was not OK!");return e.json()}).then(e=>(r.style.display="none",e.hits.length===0&&iziToast.error({fontSize:"large",close:!1,position:"topRight",messageColor:"white",timeout:2e3,backgroundColor:"red",message:"Sorry, there are no images matching your search query. Please try again!"}),e)).catch(e=>console.error("Error fetching data:",e))}const f=document.querySelector(".gallery");function p(i,r){const s=i.hits.map(e=>`<div class="gallery-item">
      <a class="gallery-link" href="${e.largeImageURL}">
          <img class="gallery-image" src="${e.webformatURL}" alt="${e.tags}">
      </a>
      <div class="gallery-image-info">
          <p class="image-info-item"><span class="image-items-text">Likes: </span>${e.likes}</p>
          <p class="image-info-item"><span class="image-items-text">Views: </span>${e.views}</p>
          <p class="image-info-item"><span class="image-items-text">Comments: </span>${e.comments}</p>
          <p class="image-info-item"><span class="image-items-text">Downloads: </span>${e.downloads}</p>
      </div>
  </div>`).join("");f.innerHTML=s,r.refresh()}const n=document.querySelector("#searchForm"),d=document.querySelector(".gallery"),g=document.querySelector(".loader"),h=new c(".gallery-link",{captionsData:"alt",captionDelay:250});n.addEventListener("submit",y);function y(i){i.preventDefault(),d.innerHTML="";const r=n.elements.searchQuery.value.trim();console.log("Submitting form with query:",r),m(r,g).then(s=>{console.log("Data fetched successfully:",s),p(s,h)}).catch(s=>console.error("Error fetching data:",s))}
//# sourceMappingURL=commonHelpers.js.map
